-lrt required for some versions of ld
Some versions of ld are causing the following issue:
undefined reference to `clock_gettime'

https://stackoverflow.com/questions/2418157/c-error-undefined-reference-to-clock-gettime-and-clock-settime

Can be replicated with "conda install -c conda-forge gxx_linux-64", which uses "GNU ld (GNU Binutils) 2.39".